nguage: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - "sudo pip install -r requirements/common.txt --use-mirrors"
  - "sudo pip install -r requirements/dev.txt --use-mirrors"
# command to run tests
script: lettuce tests/
